package cr.ac.una.prograiv.video.domain;
// Generated 12/05/2016 02:28:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer pkIdCategoria;
     private String nombre;
     private String observaciones;
     private boolean estado;
     private Set<Peliculas> peliculases = new HashSet<Peliculas>(0);

    public Categoria() {
    }

	
    public Categoria(String nombre, boolean estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Categoria(String nombre, String observaciones, boolean estado, Set<Peliculas> peliculases) {
       this.nombre = nombre;
       this.observaciones = observaciones;
       this.estado = estado;
       this.peliculases = peliculases;
    }
   
    public Integer getPkIdCategoria() {
        return this.pkIdCategoria;
    }
    
    public void setPkIdCategoria(Integer pkIdCategoria) {
        this.pkIdCategoria = pkIdCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Peliculas> getPeliculases() {
        return this.peliculases;
    }
    
    public void setPeliculases(Set<Peliculas> peliculases) {
        this.peliculases = peliculases;
    }




}


