package cr.ac.una.prograiv.video.domain;
// Generated 12/05/2016 02:28:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private DetalleId id;
     private Pedido pedido;
     private Peliculas peliculas;
     private boolean tipo;
     private float costo;
     private Date fecha;

    public Detalle() {
    }

    public Detalle(DetalleId id, Pedido pedido, Peliculas peliculas, boolean tipo, float costo, Date fecha) {
       this.id = id;
       this.pedido = pedido;
       this.peliculas = peliculas;
       this.tipo = tipo;
       this.costo = costo;
       this.fecha = fecha;
    }
   
    public DetalleId getId() {
        return this.id;
    }
    
    public void setId(DetalleId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }
    public float getCosto() {
        return this.costo;
    }
    
    public void setCosto(float costo) {
        this.costo = costo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


