package cr.ac.una.prograiv.video.domain;
// Generated 12/05/2016 02:28:02 PM by Hibernate Tools 4.3.1



/**
 * DetalleId generated by hbm2java
 */
public class DetalleId  implements java.io.Serializable {


     private int pkIdPedido;
     private int pkIdPelicula;

    public DetalleId() {
    }

    public DetalleId(int pkIdPedido, int pkIdPelicula) {
       this.pkIdPedido = pkIdPedido;
       this.pkIdPelicula = pkIdPelicula;
    }
   
    public int getPkIdPedido() {
        return this.pkIdPedido;
    }
    
    public void setPkIdPedido(int pkIdPedido) {
        this.pkIdPedido = pkIdPedido;
    }
    public int getPkIdPelicula() {
        return this.pkIdPelicula;
    }
    
    public void setPkIdPelicula(int pkIdPelicula) {
        this.pkIdPelicula = pkIdPelicula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleId) ) return false;
		 DetalleId castOther = ( DetalleId ) other; 
         
		 return (this.getPkIdPedido()==castOther.getPkIdPedido())
 && (this.getPkIdPelicula()==castOther.getPkIdPelicula());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkIdPedido();
         result = 37 * result + this.getPkIdPelicula();
         return result;
   }   


}


