package cr.ac.una.prograiv.video.domain;
// Generated 12/05/2016 02:28:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer pkIdPedido;
     private Usuario usuario;
     private byte estado;
     private Date fecha;
     private Set<Detalle> detalles = new HashSet<Detalle>(0);

    public Pedido() {
    }

	
    public Pedido(Usuario usuario, byte estado, Date fecha) {
        this.usuario = usuario;
        this.estado = estado;
        this.fecha = fecha;
    }
    public Pedido(Usuario usuario, byte estado, Date fecha, Set<Detalle> detalles) {
       this.usuario = usuario;
       this.estado = estado;
       this.fecha = fecha;
       this.detalles = detalles;
    }
   
    public Integer getPkIdPedido() {
        return this.pkIdPedido;
    }
    
    public void setPkIdPedido(Integer pkIdPedido) {
        this.pkIdPedido = pkIdPedido;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Detalle> getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set<Detalle> detalles) {
        this.detalles = detalles;
    }




}


