package cr.ac.una.prograiv.video.domain;
// Generated 12/05/2016 02:28:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas  implements java.io.Serializable {


     private Integer pkIdPeliculas;
     private Categoria categoria;
     private String nombre;
     private String director;
     private String actorPrincipal;
     private int cantExistentes;
     private int cantAlquiladas;
     private int cantVendidas;
     private String observaciones;
     private boolean estado;
     private float costoVenta;
     private float costoAlquiler;
     private Set<Detalle> detalles = new HashSet<Detalle>(0);

    public Peliculas() {
    }

	
    public Peliculas(Categoria categoria, String nombre, String director, String actorPrincipal, int cantExistentes, int cantAlquiladas, int cantVendidas, boolean estado, float costoVenta, float costoAlquiler) {
        this.categoria = categoria;
        this.nombre = nombre;
        this.director = director;
        this.actorPrincipal = actorPrincipal;
        this.cantExistentes = cantExistentes;
        this.cantAlquiladas = cantAlquiladas;
        this.cantVendidas = cantVendidas;
        this.estado = estado;
        this.costoVenta = costoVenta;
        this.costoAlquiler = costoAlquiler;
    }
    public Peliculas(Categoria categoria, String nombre, String director, String actorPrincipal, int cantExistentes, int cantAlquiladas, int cantVendidas, String observaciones, boolean estado, float costoVenta, float costoAlquiler, Set<Detalle> detalles) {
       this.categoria = categoria;
       this.nombre = nombre;
       this.director = director;
       this.actorPrincipal = actorPrincipal;
       this.cantExistentes = cantExistentes;
       this.cantAlquiladas = cantAlquiladas;
       this.cantVendidas = cantVendidas;
       this.observaciones = observaciones;
       this.estado = estado;
       this.costoVenta = costoVenta;
       this.costoAlquiler = costoAlquiler;
       this.detalles = detalles;
    }
   
    public Integer getPkIdPeliculas() {
        return this.pkIdPeliculas;
    }
    
    public void setPkIdPeliculas(Integer pkIdPeliculas) {
        this.pkIdPeliculas = pkIdPeliculas;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getActorPrincipal() {
        return this.actorPrincipal;
    }
    
    public void setActorPrincipal(String actorPrincipal) {
        this.actorPrincipal = actorPrincipal;
    }
    public int getCantExistentes() {
        return this.cantExistentes;
    }
    
    public void setCantExistentes(int cantExistentes) {
        this.cantExistentes = cantExistentes;
    }
    public int getCantAlquiladas() {
        return this.cantAlquiladas;
    }
    
    public void setCantAlquiladas(int cantAlquiladas) {
        this.cantAlquiladas = cantAlquiladas;
    }
    public int getCantVendidas() {
        return this.cantVendidas;
    }
    
    public void setCantVendidas(int cantVendidas) {
        this.cantVendidas = cantVendidas;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public float getCostoVenta() {
        return this.costoVenta;
    }
    
    public void setCostoVenta(float costoVenta) {
        this.costoVenta = costoVenta;
    }
    public float getCostoAlquiler() {
        return this.costoAlquiler;
    }
    
    public void setCostoAlquiler(float costoAlquiler) {
        this.costoAlquiler = costoAlquiler;
    }
    public Set<Detalle> getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set<Detalle> detalles) {
        this.detalles = detalles;
    }




}


