package cr.ac.una.prograiv.video.domain;
// Generated 12/05/2016 02:28:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer pkIdUsuario;
     private String nombre;
     private String apellidos;
     private String contrasena;
     private String EMail;
     private Date fechaDeNacimiento;
     private String direccion;
     private String telTrabajo;
     private String telCelular;
     private boolean tipo;
     private boolean estado;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String apellidos, String contrasena, String EMail, Date fechaDeNacimiento, String direccion, boolean tipo, boolean estado) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.contrasena = contrasena;
        this.EMail = EMail;
        this.fechaDeNacimiento = fechaDeNacimiento;
        this.direccion = direccion;
        this.tipo = tipo;
        this.estado = estado;
    }
    public Usuario(String nombre, String apellidos, String contrasena, String EMail, Date fechaDeNacimiento, String direccion, String telTrabajo, String telCelular, boolean tipo, boolean estado, Set<Pedido> pedidos) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.contrasena = contrasena;
       this.EMail = EMail;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.direccion = direccion;
       this.telTrabajo = telTrabajo;
       this.telCelular = telCelular;
       this.tipo = tipo;
       this.estado = estado;
       this.pedidos = pedidos;
    }
   
    public Integer getPkIdUsuario() {
        return this.pkIdUsuario;
    }
    
    public void setPkIdUsuario(Integer pkIdUsuario) {
        this.pkIdUsuario = pkIdUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    
    public void setFechaDeNacimiento(Date fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelTrabajo() {
        return this.telTrabajo;
    }
    
    public void setTelTrabajo(String telTrabajo) {
        this.telTrabajo = telTrabajo;
    }
    public String getTelCelular() {
        return this.telCelular;
    }
    
    public void setTelCelular(String telCelular) {
        this.telCelular = telCelular;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


